# run with 
# gen3 job run delete-expired-objects-job
apiVersion: batch/v1
kind: Job
metadata:
  name: delete-expired-objects
spec:
  template:
    metadata:
      labels:
        app: gen3job
    spec:
      volumes:
        - name: profile-creds-volume
          secret:
            secretName: "delete-expired-objects-g3auto"
      containers:
      - name: delete-expired-objects
        GEN3_DELETE-EXPIRED-OBJECTS_IMAGE
        imagePullPolicy: Always
        volumeMounts:
          - name: profile-creds-volume
            mountPath: /mnt
      restartPolicy: Never