## Full values listed here, https://github.com/kubecost/cost-analyzer-helm-chart/blob/master/cost-analyzer/values.yaml

kubecostToken: KUBECOST_TOKEN

serviceAccount:
  create: true # Set this to false if you're bringing your own service account.
  annotations: 
    KUBECOST_SA

kubecostProductConfigs:
  cloudIntegrationSecret: cloud-integration
  clusterName: master-cluster
  projectID: AWS_ACCOUNT_ID


prometheus:
  serviceAccounts:
    server:
      create: false
      name: "THANOS_SA"
  server:
    global:
      external_labels:
        # Master cluster name
        cluster_id: "master-cluster"
        
networkCosts:
  enabled: true

thanos:
  store:
    serviceAccount: "THANOS_SA"
  compact: 
    serviceAccount: "THANOS_SA"